import ExcelJS from 'exceljs';

/**
 * Helper to clean and parse amounts into raw numbers
 */
export const parseAmountValue = (amt) => {
  if (typeof amt === 'number') return amt;
  if (!amt) return 0;
  const cleaned = amt.toString().replace(/[^0-9.-]/g, '');
  const val = parseFloat(cleaned);
  return isNaN(val) ? 0 : val;
};

/**
 * Format raw number to Indian Rupee string
 */
export const formatINR = (val) => {
  return '₹' + Number(val || 0).toLocaleString('en-IN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  });
};

/**
 * Exports transaction list to a gorgeous, executive-grade colored Excel (.xlsx) spreadsheet
 */
export const exportToProExcel = async (transactions = [], options = {}) => {
  if (!transactions || transactions.length === 0) {
    throw new Error('No transactions available to export.');
  }

  const title = options.title || 'PAYLENS FINANCIAL & TRANSACTION STATEMENT';
  const subtitle = options.subtitle || `Exported on ${new Date().toLocaleString('en-IN', { dateStyle: 'full', timeStyle: 'medium' })}`;
  const filename = options.filename || `PayLens_Statement_${new Date().toISOString().slice(0, 10)}.xlsx`;

  // Calculate summary metrics
  let totalReceived = 0;
  let totalSent = 0;
  let receivedCount = 0;
  let sentCount = 0;

  transactions.forEach((t) => {
    const amt = parseAmountValue(t.amount);
    const isReceived = (t.type || '').toLowerCase().includes('receive') || (t.type || '').toLowerCase().includes('credit');
    if (isReceived) {
      totalReceived += amt;
      receivedCount++;
    } else {
      totalSent += amt;
      sentCount++;
    }
  });

  const netBalance = totalReceived - totalSent;

  // Create Excel Workbook
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'PayLens Financial Engine';
  workbook.lastModifiedBy = options.userName || 'PayLens User';
  workbook.created = new Date();
  workbook.modified = new Date();

  const worksheet = workbook.addWorksheet('Transactions & Statement', {
    views: [{ showGridLines: true }],
    properties: { defaultRowHeight: 20 }
  });

  // Define Columns (10 Standard Schema + Index)
  worksheet.columns = [
    { key: 'sno', width: 6 },                                    // A: #
    { key: 'date', width: 14 },                                   // B: Date
    { key: 'time', width: 12 },                                   // C: Time
    { key: 'transactionDetails', width: 28 },                    // D: Transaction Details
    { key: 'otherDetails', width: 24 },                          // E: Other Details (UPI ID / A/c No)
    { key: 'yourAccount', width: 18 },                           // F: Your Account
    { key: 'amount', width: 16 },                                // G: Amount (INR)
    { key: 'upiRefNo', width: 20 },                              // H: UPI Ref No.
    { key: 'orderId', width: 20 },                               // I: Order ID
    { key: 'remarks', width: 22 },                               // J: Remarks
    { key: 'tags', width: 16 }                                   // K: Tags
  ];

  // ==========================================
  // ROW 1: HEADER TITLE BANNER (Indigo/Navy)
  // ==========================================
  worksheet.mergeCells('A1:K1');
  const titleCell = worksheet.getCell('A1');
  titleCell.value = `🏛️  ${title.toUpperCase()}`;
  titleCell.font = {
    name: 'Calibri',
    size: 16,
    bold: true,
    color: { argb: 'FFFFFFFF' }
  };
  titleCell.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF1E1B4B' } // Deep indigo/navy #1E1B4B
  };
  titleCell.alignment = { vertical: 'middle', horizontal: 'center' };
  worksheet.getRow(1).height = 36;

  // ==========================================
  // ROW 2: SUBTITLE & METADATA BAR
  // ==========================================
  worksheet.mergeCells('A2:K2');
  const subCell = worksheet.getCell('A2');
  subCell.value = `${subtitle}  •  Total Transactions: ${transactions.length}  •  Generated by PayLens Pro`;
  subCell.font = {
    name: 'Calibri',
    size: 10,
    italic: true,
    color: { argb: 'FFE0E7FF' } // Indigo light #E0E7FF
  };
  subCell.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF312E81' } // Rich Indigo #312E81
  };
  subCell.alignment = { vertical: 'middle', horizontal: 'center' };
  worksheet.getRow(2).height = 22;

  // Blank spacing row 3
  worksheet.getRow(3).height = 10;

  // ==========================================
  // ROW 4: KPI SUMMARY CARDS
  // ==========================================
  worksheet.getRow(4).height = 32;

  // Inflow Card (B4:D4)
  worksheet.mergeCells('B4:D4');
  const inflowCell = worksheet.getCell('B4');
  inflowCell.value = `📥 TOTAL RECEIVED: ${formatINR(totalReceived)} (${receivedCount})`;
  inflowCell.font = { name: 'Calibri', size: 10, bold: true, color: { argb: 'FF14532D' } };
  inflowCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFDCFCE7' } }; // Emerald light #DCFCE7
  inflowCell.alignment = { vertical: 'middle', horizontal: 'center' };
  inflowCell.border = {
    top: { style: 'thin', color: { argb: 'FF86EFAC' } },
    left: { style: 'thin', color: { argb: 'FF86EFAC' } },
    bottom: { style: 'thin', color: { argb: 'FF86EFAC' } },
    right: { style: 'thin', color: { argb: 'FF86EFAC' } }
  };

  // Outflow Card (E4:G4)
  worksheet.mergeCells('E4:G4');
  const outflowCell = worksheet.getCell('E4');
  outflowCell.value = `📤 TOTAL SENT: ${formatINR(totalSent)} (${sentCount})`;
  outflowCell.font = { name: 'Calibri', size: 10, bold: true, color: { argb: 'FF7F1D1D' } };
  outflowCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFEE2E2' } }; // Rose light #FEE2E2
  outflowCell.alignment = { vertical: 'middle', horizontal: 'center' };
  outflowCell.border = {
    top: { style: 'thin', color: { argb: 'FFFCA5A5' } },
    left: { style: 'thin', color: { argb: 'FFFCA5A5' } },
    bottom: { style: 'thin', color: { argb: 'FFFCA5A5' } },
    right: { style: 'thin', color: { argb: 'FFFCA5A5' } }
  };

  // Net Balance Card (H4:K4)
  worksheet.mergeCells('H4:K4');
  const netCell = worksheet.getCell('H4');
  netCell.value = `⚖️ NET SETTLEMENT: ${formatINR(netBalance)}`;
  netCell.font = {
    name: 'Calibri',
    size: 11,
    bold: true,
    color: { argb: netBalance >= 0 ? 'FF15803D' : 'FFB91C1C' }
  };
  netCell.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: netBalance >= 0 ? 'FFF0FDF4' : 'FFFEF2F2' }
  };
  netCell.alignment = { vertical: 'middle', horizontal: 'center' };
  netCell.border = {
    top: { style: 'medium', color: { argb: 'FF6366F1' } },
    left: { style: 'medium', color: { argb: 'FF6366F1' } },
    bottom: { style: 'medium', color: { argb: 'FF6366F1' } },
    right: { style: 'medium', color: { argb: 'FF6366F1' } }
  };

  // Blank spacing row 5
  worksheet.getRow(5).height = 10;

  // ==========================================
  // ROW 6: TABLE HEADERS (10 Standard Fields)
  // ==========================================
  const headers = [
    '#',
    'Date',
    'Time',
    'Transaction Details',
    'Other Details (UPI ID / A/c No)',
    'Your Account',
    'Amount (₹)',
    'UPI Ref No.',
    'Order ID',
    'Remarks',
    'Tags'
  ];

  const headerRow = worksheet.getRow(6);
  headerRow.values = headers;
  headerRow.height = 28;

  headerRow.eachCell((cell) => {
    cell.font = {
      name: 'Calibri',
      size: 11,
      bold: true,
      color: { argb: 'FFFFFFFF' }
    };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF0F172A' } // Slate 900 #0F172A
    };
    cell.alignment = { vertical: 'middle', horizontal: 'center' };
    cell.border = {
      top: { style: 'medium', color: { argb: 'FF475569' } },
      bottom: { style: 'medium', color: { argb: 'FF475569' } },
      left: { style: 'thin', color: { argb: 'FF334155' } },
      right: { style: 'thin', color: { argb: 'FF334155' } }
    };
  });

  // ==========================================
  // TRANSACTION DATA ROWS
  // ==========================================
  let currentRowIdx = 7;

  transactions.forEach((tx, idx) => {
    const row = worksheet.getRow(currentRowIdx);
    const amtNum = parseAmountValue(tx.amount);
    const isReceived = (tx.type || '').toLowerCase().includes('receive') || (tx.type || '').toLowerCase().includes('credit');

    const dateVal = tx.date || (tx.dateTime ? tx.dateTime.split(/[\s,]+/)[0] : '-');
    const timeVal = tx.time || (tx.dateTime ? (tx.dateTime.match(/\b([0-1]?[0-9]:[0-5][0-9](?::[0-5][0-9])?\s*(?:AM|PM|am|pm)?)\b/)?.[1] || '-') : '-');
    const detailsVal = tx.transactionDetails || (isReceived ? tx.from : tx.to) || '-';
    const otherVal = tx.otherDetails || (isReceived ? tx.to : tx.from) || '-';
    const myAccVal = tx.yourAccount || '-';
    const upiRefVal = tx.upiRefNo || tx.transactionId || '-';
    const orderIdVal = tx.orderId || '-';
    const remarksVal = tx.remarks || '-';
    const tagsVal = tx.tags || (isReceived ? 'UPI Inflow' : 'Payment');

    row.values = [
      idx + 1,
      dateVal,
      timeVal,
      detailsVal,
      otherVal,
      myAccVal,
      amtNum,
      upiRefVal,
      orderIdVal,
      remarksVal,
      tagsVal
    ];

    row.height = 24;

    // Zebra striping background
    const isEven = idx % 2 === 0;
    const defaultBgColor = isEven ? 'FFFFFFFF' : 'FFF8FAFC'; // Pure white vs Slate 50

    row.eachCell({ includeEmpty: true }, (cell, colNumber) => {
      // Base cell borders
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } }
      };

      cell.font = { name: 'Calibri', size: 10, color: { argb: 'FF1E293B' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: defaultBgColor }
      };
      cell.alignment = { vertical: 'middle', horizontal: 'left' };

      // S.No (Col 1)
      if (colNumber === 1) {
        cell.alignment = { vertical: 'middle', horizontal: 'center' };
        cell.font = { name: 'Calibri', size: 9, bold: true, color: { argb: 'FF64748B' } };
      }

      // Date (Col 2) & Time (Col 3)
      if (colNumber === 2 || colNumber === 3) {
        cell.alignment = { vertical: 'middle', horizontal: 'center' };
        cell.font = { name: 'Consolas', size: 9.5, color: { argb: 'FF334155' } };
      }

      // Transaction Details (Col 4)
      if (colNumber === 4) {
        cell.font = { name: 'Calibri', size: 10, bold: true, color: { argb: 'FF0F172A' } };
      }

      // Other Details (Col 5)
      if (colNumber === 5) {
        cell.font = { name: 'Consolas', size: 9, color: { argb: 'FF4338CA' } };
      }

      // Amount (Col 7)
      if (colNumber === 7) {
        cell.alignment = { vertical: 'middle', horizontal: 'right' };
        cell.numFmt = '"₹ "#,##0.00;[Red]"-₹ "#,##0.00;"₹ "0.00';
        cell.font = {
          name: 'Calibri',
          size: 11,
          bold: true,
          color: { argb: isReceived ? 'FF15803D' : 'FFBE123C' }
        };
      }

      // UPI Ref No. (Col 8) & Order ID (Col 9)
      if (colNumber === 8 || colNumber === 9) {
        cell.alignment = { vertical: 'middle', horizontal: 'center' };
        cell.font = { name: 'Consolas', size: 9, color: { argb: 'FF475569' } };
      }

      // Tags (Col 11)
      if (colNumber === 11) {
        cell.alignment = { vertical: 'middle', horizontal: 'center' };
        cell.font = { name: 'Calibri', size: 9, bold: true, color: { argb: isReceived ? 'FF15803D' : 'FF6366F1' } };
      }
    });

    currentRowIdx++;
  });

  // ==========================================
  // SUMMARY FOOTER ROW (Double Underline Accounting Style)
  // ==========================================
  worksheet.getRow(currentRowIdx).height = 28;
  worksheet.mergeCells(`A${currentRowIdx}:F${currentRowIdx}`);
  const summaryLabelCell = worksheet.getCell(`A${currentRowIdx}`);
  summaryLabelCell.value = 'TOTAL TRANSACTIONS VALUE / NET SUMMARY:';
  summaryLabelCell.font = { name: 'Calibri', size: 11, bold: true, color: { argb: 'FF0F172A' } };
  summaryLabelCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE2E8F0' } };
  summaryLabelCell.alignment = { vertical: 'middle', horizontal: 'right' };
  summaryLabelCell.border = {
    top: { style: 'thin', color: { argb: 'FF94A3B8' } },
    bottom: { style: 'double', color: { argb: 'FF0F172A' } },
    left: { style: 'thin', color: { argb: 'FF94A3B8' } },
    right: { style: 'thin', color: { argb: 'FF94A3B8' } }
  };

  const summaryAmountCell = worksheet.getCell(`G${currentRowIdx}`);
  summaryAmountCell.value = {
    formula: `SUM(G7:G${currentRowIdx - 1})`,
    result: totalReceived + totalSent
  };
  summaryAmountCell.numFmt = '"₹ "#,##0.00';
  summaryAmountCell.font = { name: 'Calibri', size: 12, bold: true, color: { argb: 'FF0F172A' } };
  summaryAmountCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFCBD5E1' } };
  summaryAmountCell.alignment = { vertical: 'middle', horizontal: 'right' };
  summaryAmountCell.border = {
    top: { style: 'thin', color: { argb: 'FF94A3B8' } },
    bottom: { style: 'double', color: { argb: 'FF0F172A' } },
    left: { style: 'thin', color: { argb: 'FF94A3B8' } },
    right: { style: 'thin', color: { argb: 'FF94A3B8' } }
  };

  worksheet.mergeCells(`H${currentRowIdx}:K${currentRowIdx}`);
  const summarySyncCell = worksheet.getCell(`H${currentRowIdx}`);
  summarySyncCell.value = `Verified Total Records: ${transactions.length}`;
  summarySyncCell.font = { name: 'Calibri', size: 9.5, bold: true, color: { argb: 'FF475569' } };
  summarySyncCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE2E8F0' } };
  summarySyncCell.alignment = { vertical: 'middle', horizontal: 'center' };
  summarySyncCell.border = {
    top: { style: 'thin', color: { argb: 'FF94A3B8' } },
    bottom: { style: 'double', color: { argb: 'FF0F172A' } },
    left: { style: 'thin', color: { argb: 'FF94A3B8' } },
    right: { style: 'thin', color: { argb: 'FF94A3B8' } }
  };

  // Generate buffer and trigger browser download
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Enhanced Clean UTF-8 CSV Export (10 Standard Schema)
 */
export const exportToCleanCSV = (transactions = [], filename = null) => {
  if (!transactions || transactions.length === 0) {
    throw new Error('No transactions available to export.');
  }

  const exportFilename = filename || `PayLens_Transactions_${new Date().toISOString().slice(0, 10)}.csv`;

  const headers = [
    'Date',
    'Time',
    'Transaction Details',
    'Other Transaction Details (UPI ID or A/c No)',
    'Your Account',
    'Amount',
    'UPI Ref No.',
    'Order ID',
    'Remarks',
    'Tags'
  ];

  const rows = transactions.map((t) => {
    const isReceived = (t.type || '').toLowerCase().includes('receive') || (t.type || '').toLowerCase().includes('credit');
    const dateVal = t.date || (t.dateTime ? t.dateTime.split(/[\s,]+/)[0] : '');
    const timeVal = t.time || (t.dateTime ? (t.dateTime.match(/\b([0-1]?[0-9]:[0-5][0-9](?::[0-5][0-9])?\s*(?:AM|PM|am|pm)?)\b/)?.[1] || '') : '');
    const detailsVal = t.transactionDetails || (isReceived ? t.from : t.to) || '';
    const otherVal = t.otherDetails || (isReceived ? t.to : t.from) || '';
    const myAccVal = t.yourAccount || '';
    const upiRefVal = t.upiRefNo || t.transactionId || '';
    const orderIdVal = t.orderId || '';
    const remarksVal = t.remarks || '';
    const tagsVal = t.tags || (isReceived ? 'Inflow' : 'Outflow');

    return [
      `"${dateVal.replace(/"/g, '""')}"`,
      `"${timeVal.replace(/"/g, '""')}"`,
      `"${detailsVal.replace(/"/g, '""')}"`,
      `"${otherVal.replace(/"/g, '""')}"`,
      `"${myAccVal.replace(/"/g, '""')}"`,
      `"${t.amount || ''}"`,
      `"${upiRefVal.replace(/"/g, '""')}"`,
      `"${orderIdVal.replace(/"/g, '""')}"`,
      `"${remarksVal.replace(/"/g, '""')}"`,
      `"${tagsVal.replace(/"/g, '""')}"`
    ];
  });

  const csvContent = '\uFEFF' + [headers.join(','), ...rows.map((r) => r.join(','))].join('\r\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', exportFilename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
